version: 1.0.{build}
configuration: Release

branches:
  only:
    - master

install:
  - nuget restore

build:
  project: RingCentral.sln
  verbosity: minimal

environment:
  COVERALLS_REPO_TOKEN:
    secure: 1B9IN5tlBPd0C6gWAOLe9/9XjQAyvhgbNjbbfqHxJWptj2Iq4pIFapbkbcCwpRqh

test_script:
- ps: >-
    .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:".\packages\xunit.runner.console.2.2.0-beta2-build3300\tools\xunit.console.exe" -targetargs:"RingCentral.Test\bin\$env:CONFIGURATION\RingCentral.Test.dll -noshadow -appveyor" -filter:"+[RingCentral]* -[RingCentral.Test]*" -output:opencoverCoverage.xml

    .\packages\coveralls.net.0.6.0\tools\csmacnz.Coveralls.exe --opencover -i opencoverCoverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID